### ISSUE TITLE
Improve release publish

### ISSUE THREAD

**Issue by kilork** [hd-gmbh-dev/quick-microservice-rs#101]
Current implementation uses unmaintained action, should be update to this one, for example:

```yaml
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ github.ref_name }}
          tag: ${{ github.ref }}
```
